version: "3.9"

services:
  app:
    image: node:18.12-alpine
    command: sh -c "npm i && npm run migrate && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgresql://postgres:root@host.docker.internal:5432/crudUser
      TOKEN_SECRET: ded84489ab33802cb4f51aa5ee3a76b2d03d9612013de709c3f12d9277175a1c9c514c0cb7bb48231544f1352f75823105509c13ff22db355c4c3694986b7b3e
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGUSER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
